# Generated by Django 5.0.8 on 2024-08-20 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20240819_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='seat_percentage',
        ),
        migrations.AlterField(
            model_name='account',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Suspended', 'Suspended')], default='Inactive', max_length=10),
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('otp_token_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('otp_expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
